version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    command: --check-caps false
    restart: always
    ports: 
      - 1972
      - 52773
      - 53773
    volumes:
      - ./:/irisdev/app
